### PR TITLE
xGov -150 - Cross-Chain community promotion and collaberation

### PR DESCRIPTION
**Pull request by Ambassador-linnen**
Thank you for considering this proposal for cross-chain activities to boost the algorand eccosystem.

### CODE REVIEW

**Review by Ambassador-linnen — COMMENTED** [review]
Editing

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by Ambassador-linnen** [comment]
> Proposer, please post your algorand forum discussion thread link here. Thank you.

https://forum.algorand.org/t/xgov-proposal-150-cross-chain-community-promotion-and-collaberation/11098/16

**Comment by Ambassador-linnen** [comment]
A link to our forum post. 

https://forum.algorand.org/t/xgov-proposal-150-cross-chain-community-promotion-and-collaberation/11098/16

**Pull request merged**
