### PR TITLE
xGov-117 - Contract Based Wallet Abstraction

### PR DESCRIPTION
**Pull request by kylebeee**
Wallet Abstraction for bringing in the masses!

### CODE REVIEW

**Comment by Vidhyanandcs** [comment]
Liked the idea of Contract Based Wallet Abstraction

**Comment by Vidhyanandcs** [comment]
The numbers on proposal headings seems to be wrong.
xGov-116 should be replaced with xGov-117 because your pr number is 117

**Comment by kylebeee** [comment]
It's still a draft and will likely change quite a bit. Initially i was going to submit this xgov proposal to design the implementation and create the ARC but after speaking with Joe about the approach he ran with it and quickly got a prototype going. 

There's still a ton that needs to be done, so what i will likely do is break this into milestone. The first being a production ready version of the contract. The next will be a large set of plugins. After that it will be tooling to make using abstracted wallets easier & finally a focus on building out web2 auth / social signin with google/apple/email and additional other sign in methods like eth/sol/etc.

I'll try to update this draft soon to better illustrate this in detail. Thank you for your question @mangoplane !

**Comment by xxiled-plastic-cat** [comment]
Hey! Love the idea. Would you be able to provide a bit more detail on how the implementation is expected to work in the wild?

For instance, say I'm completely new to blockchain but my friends keep telling me about this great community called Akita - how does it work if I want to sign up with Apple ID for instance?

If you're able to talk to how emails/third party auth is tied to wallets etc that'd be awesome.

**Comment by kylebeee** [comment]
Hey @xxiled-plastic-cat !

I removed mention of social sign in, @mangoplane has been working on social login stuff for a while & has an xGov proposal #119 so I will likely use his in conjunction with this. So you'll be able to use that or if you'd rather take a hybrid custody approach you can mint these wallets on behalf of your web2 authenticated users and control them for them until they decide they want control ( which is great because contracts dont have keys you need to manage for the user! )

**Comment by kylebeee** [comment]
The completed smart contract work delivers exactly what the grant proposal set out to do - a production-ready plugin-based account abstraction system for Algorand. It handles all the key functionality: creating abstracted accounts with admin controls, managing plugins with time-bound permissions and cooldowns, and safely handling temporary rekeys that always verify the account returns back to the contract’s control. It includes features for adding/removing both standard and named plugins, granular permission controls (including the ability to delegate admin privileges to plugins), and options for caller-specific or global plugin access. The implementation tackles the proposal’s main goal of abstracting wallets via delegated authorizations, while keeping things secure with built-in safeguards like expiration rounds, cooldowns, and mandatory rekey verification to ensure the abstracted account always returns to the contract’s control after a plugin runs.

Submission for this Grant can be found [here](https://github.com/kylebeee/arc58-smart-wallet).
The core contract ( the actual wallet contract ) can be found [here](https://github.com/kylebeee/arc58-smart-wallet/blob/main/contracts/abstracted_account.algo.ts)

**Pull request merged**
