### PR TITLE
xGov-142: Composable Marketplace by Asalytic

### PR DESCRIPTION
**Pull request by Vilijan**
Thank you for reviewing the proposal.

### CODE REVIEW

**Comment by Vidhyanandcs** [comment]
composable marketplace is a good strategy. this will bring whole NFT ecosystem into one umbrella.

**Comment by xxiled-plastic-cat** [comment]
This is great, means that anyone can sell NFTs, sans marketplace. Be interesting to add some extra templated UI on top so anyone could have their own NFT shop if they wanted!

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by Vilijan** [comment]
> Proposer, please post your algorand forum discussion thread link here. Thank you.

Hey, where I can find that?

**Pull request merged**
