### PR TITLE
xGov 162: ASA.Gold

### PR DESCRIPTION
**Pull request by scholtz**

### CODE REVIEW

**Comment by dragmz** [comment]
What are the open source deliverables here? Are there any closed source deliverables?

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by scholtz** [comment]
> Proposer, please post your algorand forum discussion thread link here. Thank you.

https://forum.algorand.org/t/xgov-prop-162-asa-gold-introduction-video/11366

**Comment by scholtz** [comment]
Here is the deliverable: https://youtu.be/rbltuKC228g

**Pull request merged**
