### PR TITLE
xGov-98 - Launch of Nimblr: Audits, Licensing, Go Live

### PR DESCRIPTION
**Pull request by ahrevival**
Thanks for taking the time to review the Nimblr proposal. We look forward to building with you.

### CODE REVIEW

**Review by ahrevival — COMMENTED** [review]
made changes to proposal content to be more clear on the direction and allocation of funds.

**Comment by SudoWeezy** [comment]
Be sure to change the status to Final if you want to be part of the next session 
`status: Draft` -> `status: Final`

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by ahrevival** [comment]
Thanks for the reminder. I just set up the forum and it is waiting for approval.

**Comment by ahrevival** [comment]
https://forum.algorand.org/t/xgov-98-launch-of-nimblr-audits-licensing-go-live/11348

**Review by ahrevival — COMMENTED** [review]
Update discussion post

**Comment by ahrevival** [comment]
Just want to be sure you got this email.

**Pull request merged**
