### PR TITLE
xGov-38 - Decentralized Perpetual Margin Exchange

### PR DESCRIPTION
**Pull request by grzracz**

### CODE REVIEW

**Comment by NSindre** [comment]
Doesn't Deflex already do all three? https://www.deflex.fi/

**Comment by ErikHasselwander** [comment]
Deflex does part of the first, it has stableswap support and some lending pools (I think, their docs do not say what protocols are implemented from what I can tell). But Vestige is currently routing ~10% of all swaps on Algorand, so us supporting it would be a major improvement not only for us but also the individual protocols (pact, algofi, folks).

First some context. Both Vestige and Deflex both currently operate in the same way, we create qoutes off-chain that are then routed through a routing app. The purpose of our second component is to remove the off-chain creation of qoutes and move that on-chain, so that dapps can get access to aggregated liquidity without relying on any centralized infrastructure. This is not something that Deflex has implemented, their on-chain part is only an interface that gets fed off-chain data, just like our current router is.

I will also add that the two first components include research and results that will be directly used in the perpetuals futures market we're building. This exchange will rely completely on a decentralized aggregator to remove any point of centralization while also allowing the protocol itself to do it's own liquidations, order openings and order closings.

**Comment by NSindre** [comment]
Good clarification, thank you.

**Comment by DragonFi-Realm** [comment]
🐉🔥 High priority for Algorand DeFi

**Pull request merged**
