### PR TITLE
xGov-123: AlgoDirectory (directory.algo)

### PR DESCRIPTION
**Pull request by SilentRhetoric**

### CODE REVIEW

**Comment by kylebeee** [comment]
Hey Silent, can you explain to me how this is different than arc53 aside from being forced to buy a directory.algo segment & listings expiring?

**Comment by SilentRhetoric** [comment]
@kylebeee The proposed ARC-53 standard ("A specification for a decentralized, Self-declared, & Verifiable Tokens, Collections, & Metadata") could certainly be utilized in directory listings to provide structured data for tokens and collections.  

The Directory is not going to be opinionated about how listings are defined beyond some core fields.  It could be possible, for example, to have one listing that self-identifies as ARC-53 and displays as such in the UI while another listing (for which ARC-53 is not relevant) follows a schema such as schema.org and displays differently.  

Once the core open source platform is created, the community could contribute additional ways to visualize listing data for various schema or even treat the directory as a white-label product that could be forked, rebranded, and customized for specific purposes.

**Comment by kylebeee** [comment]
Would highly recommend utilizing it or even extending it! When i proposed it, directory.algo was top of mind as a use case for it and i made sure it was an extensible, living standard so that things like schema.org could be added to it.

**Comment by SudoWeezy** [comment]
Be sure to change the status to Final if you want to be part of the next session 
`status: Draft` -> `status: Final`

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Pull request merged**
