### PR TITLE
Proposal for xGov 14

### PR DESCRIPTION
**Pull request by 0xLiquidGlass**

### CODE REVIEW

**Comment by nonfungibleab** [comment]
Congratulations! xGov voting session 1 is now closed and your proposal has passed. I need your email to kick off contract signature next week. Would you please send me a DM on Twitter or Discord?

**Comment by 0xLiquidGlass** [comment]
> Congratulations! xGov voting session 1 is now closed and your proposal has passed. I need your email to kick off contract signature next week. Would you please send me a DM on Twitter or Discord?

@nonfungibleab 

Hi Adri. Unfortunately, I was not able to send you a friend request as well as PM on Discord. I will be sending you a PM on Twitter instead

**Comment by nonfungibleab** [comment]
Hi @0xLiquidGlass I've sent you a couple of messages on your gmail address. Did you get them? We are keen to start the contract process. Would you be able to email governance@algorand.foundation to get the process started, please?

**Comment by nonfungibleab** [comment]
Hi @0xLiquidGlass did you message the governance address above? I haven't seen the email come through from you. We would like to get the contract signed to organise payment. Thank you.

**Comment by 0xLiquidGlass** [comment]
@nonfungibleab Unfortunately, even though the xGov proposal for Unnamed Wallet had passed, we will not proceed with the contract

**Comment by nonfungibleab** [comment]
Thanks for letting us know @0xLiquidGlass

**Pull request merged**
