### PR TITLE
xGov-151: Honeypot

### PR DESCRIPTION
**Pull request by concernedxgov**

### CODE REVIEW

**Comment by dragmz** [comment]
🐝

**Comment by madshapes-dev** [comment]
the problem is, this proposal doesn't really solve the issue, but it still takes away votes form the total vote allocation. honeypot proposal needs to be introduced by the xgov team with accompanying method to "fix" the votes

**Comment by concernedxgov** [comment]
> the problem is, this proposal doesn't really solve the issue, but it still takes away votes form the total vote allocation. honeypot proposal needs to be introduced by the xgov team with accompanying method to "fix" the votes / penalize the voters

Completely agree. This proposal will only help to reveal if there really is a problem with bots/people not reading. If this turns out to be the case, the xgov team can focus on the issue, which has not been taken seriously enough so far.

**Comment by SilentRhetoric** [comment]
@nonfungibleab @trekianov Can you confirm if AF plans to have a real honeypot or not?

**Pull request closed without merging**
