### PR TITLE
xGov-145: Providing content to encourage on-chain activities among Algorand's Japanese users and acquiring new users.

### PR DESCRIPTION
**Pull request by apar0xmei**
Thank you for considering my proposal

### CODE REVIEW

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by apar0xmei** [comment]
@nonfungibleab 
I apologize for the delayed response. While we have a dedicated space on Discord for discussing proposals, is it necessary to post on the Algorand forum as well? Additionally, is it required to take action after receiving favorable votes this time? Thank you.

**Comment by nonfungibleab** [comment]
Hi @apar0xmei congrats on your grant application approval! We need your email to send comms about contract details.

**Comment by apar0xmei** [comment]
> Hi @apar0xmei congrats on your grant application approval! We need your email to send comms about contract details.


Thank you for reaching out.
My contact information is as follows.

n_yamamoto_al@outlook.jp

**Comment by nonfungibleab** [comment]
Thank you!

**Comment by apar0xmei** [comment]
I will report the consolidated results of this proposal on this thread.
For daily updates, I will report them on the xgov145discussion thread on the Algorand Japan Discord.
https://discord.gg/JzTjpkf79N

**Pull request merged**
