### PR TITLE
xGov 164: Prague community meetup

### PR DESCRIPTION
**Pull request by scholtz**

### CODE REVIEW

**Comment by dragmz** [comment]
What are the open source deliverables here? Are there any closed source deliverables?

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by scholtz** [comment]
> Proposer, please post your algorand forum discussion thread link here. Thank you.

https://forum.algorand.org/t/xgov-prop-164-prague-community-meetup/11368

**Comment by scholtz** [comment]
This xGov request is already green, so we started to organize the event.

We booked the [Paralel Polis](https://www.paralelnipolis.cz/) location one day before the start of ETH Prague.

Mark your calendar for **May 30, 18:30 to 22:00**. We will join forces with regular BeerFi Prague meetup.

Check other events you might be interested during the Prague Blockchain Weeks 2024

https://docs.google.com/spreadsheets/d/1D26eQIvj6WitYJUjgOvLRD5kBtooy3eg9TKgRWtnP2s/edit#gid=1535357668

**Pull request merged**
