### PR TITLE
xGov 165: Proposal to build NFT Bridge between Algorand and EVM based networks

### PR DESCRIPTION
**Pull request by FoundryKev**
Thank you for considering our proposal!

### CODE REVIEW

**Comment by dragmz** [comment]
What are the open source deliverables here? Are there any closed source deliverables?

**Comment by FoundryKev** [comment]
@SudoWeezy Hi! I see you changed the title of our request and added about updating before period 3.
Can you please specify in more detail what we should do? Also, I think some of the characters you used in the new title are causing checks to fail.

**Comment by SudoWeezy** [comment]
All good now, a section was missing, I added ```Additional information```

**Comment by SudoWeezy** [comment]
Be sure to change the status to Final if you want to be part of the next session 
`status: Draft` -> `status: Final`

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Pull request merged**
