### PR TITLE
Proposal to build a Humble.sh connector for Hummingbot client

### PR DESCRIPTION
**Pull request by tinchosig**
Proposal for CoinAlpha to build a Humble.sh connector to the Hummingbot client, the most widely used open source market making bot.

### CODE REVIEW

**Comment by nonfungibleab** [comment]
Hi, please engage with the community at the Algorand Forum. 
https://forum.algorand.org/t/xgov-39-humble-sh-hummingbot-connector/9911

**Comment by SudoWeezy** [comment]
Nothing more on your side, people will vote on proposals when we start the process

**Comment by tinchosig** [comment]
Great.

When does the voting process begin?

Thanks,

*Martin Sigwald*

*Business Development Manager**Telegram: @tinchosig*
*CoinAlpha <http://coinalpha.com/> | Hummingbot <http://hummingbot.org/>*

**Comment by tinchosig** [comment]
Hi all,

On the community discussion thread someone suggested we add Pact.fi to the
proposal, since it has more volume than humble.
Would it be possible to edit the proposal to include that inside the scope
and adjust the total amount of the grant (since extra work would be
required)? Or do you think it would make more sense to put in a separate
proposal for pact.fi?
The benefit of bundling them is that the overall number would be lower that
if we submit to grant requests, since we would need to put in roughly the
same amount for both, given the risk of one passing and the other not.

Please advise.

Thanks!

*Martin Sigwald*

*Business Development Manager**Telegram: @tinchosig*
*CoinAlpha <http://coinalpha.com/> | Hummingbot <http://hummingbot.org/>*

**Pull request merged**
