### PR TITLE
xGov-143: Solluna Mushroom Farm LLC

### PR DESCRIPTION
**Pull request by solluna168**
Thank you for considering my proposal. I'm beyond excited to share my passion with the crypto community! Blessed to work with such an innovative technology. I have no words to express how thrilled I am to be able to combine my work drive with both of my passions.

### CODE REVIEW

**Comment by solluna168** [comment]
---
id: 143
period: 3
title: Educational Fungi Farm
author: Sean Deegan 
discussions-to: https://discord.gg/2NjD3wBFf4
company_name: Solluna Mushroom Farm LLC
category: Community
focus_area: Other
open_source: Yes
amount_requested: 55000
status: Final
---

## Abstract
Solluna Mushroom Farms is a farm-to-table business that is adopting Algorand's blockchain technology to educate/onboard mushroom growers and buyers.
We aim to achieve this by implementing the following key features to our business plan: (1) an ASA (Algorand Standard Asset) rewards only program for our customers and supporters, (2) an NFT based grow kit and farming course, and (3) an innovative regenerative sustainablity mushroom farm. We are requesting funding in order to execute these key features.

## Team

#### Sean Deegan - Mycologist, Solluna168, AKA StinkyBird, Algonaut’s MOD
I have experience working in a variety of areas but am the head mycologist of this project. I am or have been in the past a Permaculture Certificate Holder, Level 2 Direct Support Professional, CDL Driver, Wireline Operator 3, Crane Operator, Crew Leader/Pile Operator, Sea Kayak Tour Guide, Alligator Trainer/Handler, Turtle Farm Caretaker, Contractor, Backup Battery Tech specializing in cell towers, Wilderness Survival Expert and Bartender. I am mechanically inclined, hardworking, and hold strong leadership skills. I have a passion for mushrooms and feel they have a lot to offer humanity. Managing my own farm and building my own team has always been a dream I have been working towards! I've encountered everything from running massive pillars, to battling alligators, to wiring explosives. Using Algorands technology, with my past work experiences, will create a fun learning enviroment for crypto and fungi. I have been a Sea Kayak Tour Leader for an extended period of time and plan to offer stand-up paddle board classes for mushroom identification. I've been guiding groups of up to 14 individuals for five years. Attending a Wilderness Survival College taught me how to live off the land, so all of my prior experiences are coming together under one roof.

#### Christian (Tako) - Full Stack Software Developer

Created Blocki, an app that determines the number of blocks proposed to the chain by a node. Runs various Algorand participation nodes since late 2021 and has assisted others with their participation nodes.

#### Andrew Kotulak – Advisor

With a background in Blockchain and Trade Finance, the University of Michigan awarded me a BA in Finance. Head of DeFi at Humble. He also oversees Algonauts, which organizes the AlgoFest event and offers advisory services to nascent blockchain enterprises. As well as, a member of the Algorand DeFi Advisory Committee.

#### Dan Folgate- Hashton-Aka Skunky's stable from tiny horse

After three years in the Algorand ecosystem, my name is Daniel Folgate. Ardent NFT collector involved in several major initiatives before thurstober.com, Mngo, and others. Possesses several coins and engages in commerce. Maybe among the select few who found success using Yieldly. Most likely, it was fortunate timing. I'm only now learning Python and SDKs. By summer, I hope to get a node running, thanks to a PC update. High volume bartender for a long period. At one point, I gave up and got my class A CDL with all the endorsements in Florida. Enthusiastic gardener for over ten years and novice mycologist. In my spare time, I like to play fingerstyle guitar.

#### Danijela Zeravica- Soil biologist certifcation, DSP, Advanced Gardener

Broad range of abilities, including advanced gardening, creating your own compost, multitasking, understanding the blockchain, CPR/First Aid, caring for others, and eventually becoming a licensed therapist in the state of Oregon. Novice mycologist.

#### Seamus Spencer- Spencer's Remodeling LLC, Solar tech

Owns a construction company that offers anything from playgrounds to solar installations and upscale bathroom makeovers. Manages a crew of five men and oversees several projects at once. We handle everything; electrician, plumbing, demo. Extremely eager to apply my abilities to the field of mushroom farming. We'll develop these environmentally friendly fungi farms and support Solluna Farms' aim. I have experience in the cryptocurrency space and am quite knowledgeable about blockchain technologies, coin swapping from DEXs, LPs, staking, and node operations.

## Experience with Algorand

- Staking
- Swapping asas
- Connecting to dapps
- NFT artist
- Running Nodes
- Dapp development 

## Present Proposal

#### SPORE Token
The farm will incorporate the SPORE token into the business model by giving holders discounts on our products. SPORE will be sent to clients that participate in our discord and Texas holdem poker tournaments.

#### NFTs
We plan on creating mushroom grow kits with NFTs associated to each type of kit. These NFTs will have information about the fungus, a spore print, how to grow and take care of your new fungus.

#### Mushroom Courses
Our courses will assist new growers with retaining existing mushroom farm practices that can be easily transferred to their own farms. These courses will also include basic understanding of the Algorand ecosystem and technology. We will be doing this in order to prepare our clients for future collaborations.

#### Environmentally Friendly Farm
Our farms will be producing fungi by using recycled plastic with outdoor elements that will assist in healthy fungus. These farms will run off solar, wind, and hydropower at some locations. Solluna Farms will be the first full scale fungi farm to use reusables!

## Future Blueprint
Online educational platform to teach crypto and fungi cultivation. Online marketplace full of wellness products, and mushroom cultivation supplies. Using the chain to track rewards for discounts using SPORE coin.

## Benefits for the community

#### Genuine Rewards Program
The SPORE token’s only purpose is as a rewards and discount token for our products. This token will not be available on decentralized exchanges or other decentralized finance applications. SPORE can be used with our products to get up to a 20% discount, the amount of SPORE needed to get the full 20% discount will be voted on by our community.

#### Educational
The on-boarding of new Algorand users will occur with each new student that completes our courses. Courses will explain how the Algorand blockchain works and how we integrate our farms with the technology.

#### Unique NFT use case
Each type of grow kit for a particular fungus will come with an NFT that provides detailed information on what the grower has purchased. This means for every grow kit sold, a grower will use the Algorand chain in order to read their instructions and get more information about the fungus.

## Additional information

#### Current clients in Oregon
- C Street Bistro - Italian cuisine
- Alchemy Restaurant and Bar - (fine dining) American style cuisine
- Participation at local farmer markets
  We have one farm up and running! Zero debt, all self funded. 

#### Environmentally focused
Cultivating fungi is not very environmentally friendly. The majority of large farms use plastics for growth and never attempt to achieve the scale and sustainability of a regenerative farm. The creative reuse of bags, the use of solar, and wind power by Solluna Farms will significantly alter the way that mushrooms are grown on a wide scale. The adoption of fungus will begin with educational courses. Since this will be the first application of NFTs in education, people will have a greater appreciation for what these devices are capable of. With practical classes offered around the state and online resources, we will instruct people on how to cultivate their own food and utilize technology responsibly in the Algorand Ecosystem.

Our two major goals will be to expand the Algorand blockchain and fungi farms. For ongoing research, the Oregon Solluna Farm will cultivate fungus with legal therapeutic properties. I currently work as a DSP for persons who have mental health issues. This product line will be put to the test in a variety of ways to demonstrate how fungi may actually benefit those in need. In the past I managed an Algorand NFT poker tournament. We had fifteen of the best NFT projects from Algorand on board. For our tournament we’ll be giving out courses, cross-chain games, mushroom rewards, and Algorand NFTs. Our hearts, souls, and considerable time has been going into this project. Working with mushrooms has shown the potential to significantly improve mental health and other health issues.

This company offers in-person workshops, mushroom foraging expeditions, and a gentle introduction to cryptocurrency and mushroom cultivation.

#### Algo Spending plan

#### Total: 55,000 Algo

| Amount | Description                                                   |
| :----: | :------------------------------------------------------------ |
| 28,000 | Solluna Farms expansion farm Oregon and Florida               |
| 10,000 | Switching farm to solar, wind power turbines, solar generator |
| 7,000  | Online marketplace supplies                                   |
| 5,000  | NFT/ASA prize fund for free texas holdem tournaments          |
| 5,000  | On boarding expenses, meet up yearly subscription             |

**Comment by SudoWeezy** [comment]
I made changes to allow your proposal to go through, you remove it. Why? It does not pass the checks anymore.

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by solluna168** [comment]
what !!!! I didn’t change anything f

**Comment by solluna168** [comment]
I really didn’t do anything or changes after getting the green light i’ll
be back on my computer after the work day hope it’s not too late …I really
didn’t edit it after getting the thumbs up from you guys idk what happened
man that would really ruin my day .
sean

**Comment by nonfungibleab** [comment]
Hi @solluna168, congrats on your grant application approval. We need your email to send comms about contract details.

**Comment by solluna168** [comment]
So sorry for the delay been beyond busy!
sollunamushrooms@gmail.com

**Pull request merged**
