### PR TITLE
xGov-47: Rand Auctions Proposal  -> To withdraw

### PR DESCRIPTION
**Pull request by KillerGasy**
Rand Auctions xGov Proposal.

Looking forward to all feedback from the community.

- Agash

### CODE REVIEW

**Comment by cswenor** [comment]
What about making it an open auction protocol that anyone can implement. That way there wouldn't be a wall garden for the auctions and then everyone could just compete via a better interface for the exact same auctions.

**Comment by Vidhyanandcs** [comment]
The proposal has multiple milestones and it has not mentioned how much it will cost to reach each milestone.

**Comment by iamwhoiamarenti** [comment]
Distributed Finance owns Rand Gallery

https://news.fintech.io/post/102hvtr/distributed-finance-raises-2-5m-in-seed-funding

Your holding company raised $2,500,000 but is now asking for $50,000 from the community ALGO to build out a basic feature for your platform?

https://twitter.com/al_goanna/status/1680002417319120896

How about your team builds something innovative for #Algorand instead of relying on the AF to subsidize your attempt at NFT feature parity? 🤣 This is disgraceful

**Comment by Vidhyanandcs** [comment]
> What about making it an open auction protocol that anyone can implement. That way there wouldn't be a wall garden for the auctions and then everyone could just compete via a better interface for the exact same auctions.

This makes the proposal innovative. @KillerGasy may be u can think of rewriting the proposal this way.

**Comment by nonfungibleab** [comment]
Hey @KillerGasy your PR is 47, could you pls rename your proposal xgov-47? Thanks

**Comment by nonfungibleab** [comment]
Please also engage with the community in the Algorand forum 
https://forum.algorand.org/t/xgov-47-nft-auction-dapp-rand-auctions/9998

**Comment by SudoWeezy** [comment]
Hello.
Please update your proposal to match the template provided here. 
[https://github.com/algorandfoundation/ARCs/blob/main/assets/arc-0034/TemplateForm.md](https://github.com/algorandfoundation/ARCs/blob/main/assets/arc-0034/TemplateForm.md)
Thanks.

**Pull request closed without merging**
