### PR TITLE
xGov-116 - Subscription Payments

### PR DESCRIPTION
**Pull request by kylebeee**
Subscription Contracts for all your automated payment needs!

### CODE REVIEW

**Comment by Vidhyanandcs** [comment]
The numbers on proposal headings seems to be wrong.
xGov-111 should be replaced with xGov-116 because your pr number is 116

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by nonfungibleab** [comment]
Hello @kylebeee Congrats on your proposal's approval! We need you email address to start the contract process.

**Pull request merged**
