### PR TITLE
xGov-109 - Unraveling Algorand's Real World Assets Landscape & DEX Swaps - by Chaintrail

### PR DESCRIPTION
**Pull request by ChainTrail**
Initial xGov proposal (draft)

### CODE REVIEW

**Comment by ChainTrail** [comment]
@SudoWeezy How can we reference a previous proposal and pass the validation? As soon as we reference 'xGov-61' the auto-validation starts to fail (as it needs to include a link, but neither markup formats seems to pass there).

**Comment by SudoWeezy** [comment]
You can do it like this `[xGov-61](https://github.com/algorandfoundation/xGov/pull/61)` Or like this if the file is in the main repo `[xGov-61](xgov-61.md)`

**Comment by ChainTrail** [comment]
@SudoWeezy hope it's still on time. But changed the abstract to something more understandable for this voting session/proposal. Thanks!

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by ChainTrail** [comment]
Forum: https://forum.algorand.org/t/xgov-109-unraveling-algorands-real-world-assets-landscape-dex-swaps/11226

**Pull request merged**
