### PR TITLE
xGov-55: GoPlausible MultiChain Proposal

### PR DESCRIPTION
**Pull request by emg110**
Proposal to XGOV initiative to request Algorand XGovs votes for a grant to make runway to develop and deliver PLAUSIBLE protocol multi-chain to stand a chance both for being profitable and to be able to meet VCs demands on being multichain! Starting with POLYGON and BSC!

### CODE REVIEW

**Comment by emg110** [comment]
Hello @nonfungibleab ! How can one change the label from s-draft to s-final?

**Comment by SudoWeezy** [comment]
Hey, @emg110,

**Comment by emg110** [comment]
Million thanks!

**Comment by emg110** [comment]
And about merging, when it will be merged @SudoWeezy

**Comment by SudoWeezy** [comment]
It will be merged before the next governance period ( We might update the template before so please keep an eye here! 

Also, you are missing few things:
-  the ##Rodamap section ( as shown here https://github.com/algorandfoundation/ARCs/blob/main/assets/arc-0034/TemplateForm.md) 
- `author: MG (@emg110), Sheghzo <@sheghzo>` should be `author: MG (@emg110), Sheghzo (@sheghzo)`
- `category` must be one of: `dApps`, `Tools`, `Community`, not `Utility/Service`

**Comment by emg110** [comment]
Thank you so much @SudoWeezy ! All items addressed and updated! Will keep an eye here for updates and implement them immediately as well! Thanks for everything!

**Comment by emg110** [comment]
> Hello. Please update your proposal to match the template provided here. https://github.com/algorandfoundation/ARCs/blob/main/assets/arc-0034/TemplateForm.md Thanks.

Are these new @SudoWeezy ? Other than the ones we went through above?

**Comment by SudoWeezy** [comment]
> > Hello. Please update your proposal to match the template provided here. https://github.com/algorandfoundation/ARCs/blob/main/assets/arc-0034/TemplateForm.md Thanks.
> 
> Are these new @SudoWeezy? Other than the ones we went through above?

Yes, current proposal -> present proposal
Remove the Period field on the header

**Comment by emg110** [comment]
Thank you so much @SudoWeezy ! Will be done this weekend! I appreciate your kind support here!

**Pull request merged**
