### PR TITLE
xgov-95: Gamify Exploration and Engagement of NFT ecosystem with Open-source browser game

### PR DESCRIPTION
**Pull request by madshapes-dev**
since nothing is merged yet... here is an extra one :)

### CODE REVIEW

**Review by madshapes-dev — COMMENTED** [review]
fix number

**Comment by madshapes-dev** [comment]
Example of the UI for the game, try demo here:  https://cosmic-match.vercel.app/
image

**Review by madshapes-dev — COMMENTED** [review]
.md

**Review by madshapes-dev — COMMENTED** [review]
updated to fit new template,
update hyperlinks
adjust asked price

**Review by madshapes-dev — COMMENTED** [review]
//

**Review by madshapes-dev — COMMENTED** [review]
//

**Review by madshapes-dev — COMMENTED** [review]
some editing add future blueprint with cross chain angle

**Review by madshapes-dev — COMMENTED** [review]
update discussions link

**Review by madshapes-dev — COMMENTED** [review]
define deliverable + timeline + funding schedule

**Review by madshapes-dev — COMMENTED** [review]
/

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Pull request merged**
