### PR TITLE
xGov-100 - GPU-based vanity address generator for Algorand

### PR DESCRIPTION
**Pull request by dragmz**
Please have a look at the proposal document. Any related questions and discussions are welcome at:
https://forum.algorand.org/t/xgov-100-gpu-based-vanity-address-generator-for-algorand/11067

### CODE REVIEW

**Comment by Vidhyanandcs** [comment]
What is the differentiating factor when compared to
https://algovanity.com/

**Comment by dragmz** [comment]
> What is the differentiating factor when compared to https://algovanity.com/

It's the performance. AlgoVanity is ~500 addrs/s on my i7-4790K and the GPU tool is ~290000 addrs/s on my good old GTX 950.

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by robdmoore** [comment]
If you get funded for this it would be neat if it can be hooked into the `algokit task vanity-address` command.

**Comment by dragmz** [comment]
> If you get funded for this it would be neat if it can be hooked into the `algokit task vanity-address` command.

That's an interesting idea and I see no problem with anyone getting it integrated into the algokit. The generator will most likely come as a ready to use importable Python module too, not just a command line tool.

**Comment by dragmz** [comment]
@nonfungibleab my email is dragmz@gmail.com

**Comment by nonfungibleab** [comment]
Thank you!

**Comment by dragmz** [comment]
The project has been delivered and the source code is available in the repository below:
https://github.com/dragmz/pyagg

I'd like to invite the community to give it a try and leave any comments / bug reports etc.

Additionally to what's been funded here with xGov, I'm also publishing a Rust port of the utility at:
https://github.com/dragmz/rsagg

The Rust port performs much better on high end GPUs like RTX.

**Comment by nonfungibleab** [comment]
Ciao Marcin, xGov-100 deliverables review has concluded and is approved to
proceed for payment.
I'll process the payment request for 47,474 Algo within the next couple of
days and let you know of the estimate pay date.
Thanks for participating in the xGov pilot and for your patience with the
lengthy process.
Best, Adri

**Pull request merged**
