### PR TITLE
xgov-96: Cosmic Champs x AlgoBots - Cross-community 3D NFT Collab

### PR DESCRIPTION
**Pull request by madshapes-dev**

### CODE REVIEW

**Review by madshapes-dev — COMMENTED** [review]
/

**Review by madshapes-dev — COMMENTED** [review]
editing, formatting

**Comment by madshapes-dev** [comment]
> editing, formatting

repurposed this proposal, as similar one was already approved for another project in previous period.

**Review by madshapes-dev — COMMENTED** [review]
//

**Review by madshapes-dev — COMMENTED** [review]
update ask and modify to be a project specific collab, instead of tba one

**Review by madshapes-dev — COMMENTED** [review]
editing

**Review by madshapes-dev — COMMENTED** [review]
update discussions link

**Review by madshapes-dev — COMMENTED** [review]
adding timeline + payment schedule

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Pull request merged**
