### PR TITLE
xGov-17 - ASA Stats Point in Time - tax reporting reference for US citizens

### PR DESCRIPTION
**Pull request by ipaleka**
ASA Stats Point in Time will bring the possibility to evaluate user accounts at any moment in the past. After the implementation, Algorand blockchain users will be able to create transparent references for tax reporting.

### CODE REVIEW

**Comment by andrew-m-higgs** [comment]
Don't like the 'for US citizens' part.

**Comment by ipaleka** [comment]
> This proposal implies the deployment of all the needed data and templates for **US citizens** tax reports for free. At the same time, users from the rest of the world will get a foundation for implementation through the ASA Stats user widgets system.

**Comment by ipaleka** [comment]
Hi @nonfungibleab !

The proposal is updated based on the latest criteria for milestone-based proposals tho I'm not directly contacted to do that, I hope this doesn't conflict with the status being Final before the change. :)

**Comment by ShaperOfEntropy** [comment]
A needed tool in the ecosystem. Reasonable cost-benefit ratio.

What I'm missing in the proposal is similar to your other proposal:
1. Analysis of the competition and existing solutions in the ecosystem and beyond. How does your project compare to them?
2. How will you get the tool to the intended users? E.g. will you do any marketing?
3. How will xGovs be able to verify the results of the research step? Will articles/reports/legal opinions be published, attestation of experts in the field, etc.?
4. Since the tool will be free to use, how will you finance its long-term maintenance, especially since the proposal states it relies on the core ASA Stats functionality?
5. How will the grant be spent? Will ALGO be sold on the market? If yes, using DEXs or CEXs? Or will a loan be taken against it in DeFi/CeFi? Or will project team members be paid directly in ALGO? Or will it go to project treasury? Or for buyback of your tokens?

Since you have multiple proposals, it raises the question whether you would be able to deliver on both of them if they both get approved, especially since you say the core functionality of ASA Stats has the highest priority.

**Comment by ipaleka** [comment]
Some questions are answered here: https://github.com/algorandfoundation/xGov/pull/26#issuecomment-1656720097

> Analysis of the competition and existing solutions in the ecosystem and beyond. How does your project compare to them?

There's [StakeTax](https://stake.tax/) that offers listings of all transactions in a period for a particular asset.

ASA Stats Point in Time will be offering values in fiat currency for the user address(es) at a specific point of time, as well as differences for a period. Our research will define the exact process.
 
> How will you get the tool to the intended users? E.g. will you do any marketing?

We haven't done any marketing so far as we didn't have a budget for it. Nevertheless, we have managed to become one of the most visited websites in the ecosystem. Also, this proposal doesn't involve any funds for marketing.

Our primary goal is to create the infrastructure and ASA Stats Offer is simply one of its parts. Once when the core development is done and the majority of initial user widgets and user settings are deployed then we'll focus on marketing.
 
> How will xGovs be able to verify the results of the research step? Will articles/reports/legal opinions be published, attestation of experts in the field, etc.?

Our research will define what would be needed to fill a tax report and the research will be published after the first milestone. The final milestone implies deployment on our website and mobile apps of the finished app.

> Since the tool will be free to use, how will you finance its long-term maintenance, especially since the proposal states it relies on the core ASA Stats functionality?

Once it is deployed, ASA Stats Offer will become the core functionality and it wouldn't be able to separate its maintenance from the rest of the engine. As we have managed to develop and maintain the project in the last 20 months with far less money and quite a lot more work, it is expected that everything goes much easier in the future.

We expect to fulfill our promises in these two xGov proposals and to get rewarded with the funds we are asking for. We see these two proposals just as the start of a very long and prosperous relationship, both in the pre-DAO phase and when the ASA Stats DAO (the shareholder/owner of the project) takes over the project,

**Comment by ipaleka** [comment]
> Congratulations! xGov voting session 1 is now closed and your proposal has passed. I need your email to kick off contract signature next week. Would you please send me a DM on Twitter or Discord?

https://github.com/algorandfoundation/xGov/issues/57#issuecomment-1702651954

My email is this username at project's domain asastats.com.

**Comment by nonfungibleab** [comment]
Got it, thanks.

**Pull request merged**
