### PR TITLE
xGov-153: Neighborhood Rideshare Project (use case)

### PR DESCRIPTION
**Pull request by willisback232**
Neighborhood Rideshare Project.  Thank you for reading and your thoughtful evaluation/consideration.

### CODE REVIEW

**Comment by xxiled-plastic-cat** [comment]
Very cool idea! 

How would you say your solution is different from current non-blockchain providers in the marketplace? And on the back of that, why blockchain?

**Comment by willisback232** [comment]
> Very cool idea!
> 
> How would you say your solution is different from current non-blockchain providers in the marketplace? And on the back of that, why blockchain?

Blockchain provides 2 advantages.  Automation of course - which reduces the amount of needed customer service reps down the road (cost savings).  It is currently thought that slashing/end-user punishment for violating the vehicle usage agreement will be automated until the violations become profuse (exact cut-off to be evaluated/delineated later) whereby they must convince a review board that they deserve one more chance to have their privilege to use the service restored.  The other advantage is that early on, the project tokens function more like shares of stock in the company.  This allows the target audience the opportunity to fund the project (and profit from it) - the exact same target audience that the project aims to be of meaningful assistance to.
For the second part, we are not aware of any company already doing this - allowing users to operate company assets in the described manner.  If there are any, please enlighten me.  I'm aware of companies that make agreements with owners to allow third-party usage - but the automation of blockchain should allow our company to implement this functionality on a more meaningful (partial day) basis.  I envision the vehicles being used 3-4 out of the available 8 blocks per day.
Lots of work/cost evaluations, et cetera will be needed going forward.  But we think the principle is sound/viable enough to get the ball rolling and see where the journey leads.  It's the type of project that may not be able to reach our ultimate goal, but the learning/research completed should have a meaningful impact in one way or another - leading to a more inclusive/prosperous economy.  
Thanks for the comment/interest, hope your exile is close to termination :-)

**Comment by xxiled-plastic-cat** [comment]
Thanks for info.

In terms of other companies, at least in the U.K. I know of Co wheels [co wheels](https://www.co-wheels.org.uk/?gclid=EAIaIQobChMIoJDQ-NfvgwMV2Z2DBx3raAZZEAAYASAAEgLvYvD_BwE)

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Pull request merged**
