### PR TITLE
xGov-99 - AlgoLearn Platform; Open-sourced Lecture Series

### PR DESCRIPTION
**Pull request by atsoc1993**

### CODE REVIEW

**Comment by Vidhyanandcs** [comment]
Algorand developers youtube channel is creating and updating the lecture series on TEAL, PyTEAL and may be on PUYA.
What added value can be generated by this proposal?
https://www.youtube.com/@algodevs

**Comment by atsoc1993** [comment]
> Algorand developers youtube channel is creating and updating the lecture series on TEAL, PyTEAL and may be on PUYA. What added value can be generated by this proposal? https://www.youtube.com/@algodevs

Hi AP, happy holidays and Merry Christmas!

I'm a big fan of the @algodevs YouTube channel. However, I've struggled to implement the content they cover and have mostly learned independently aside from a question here and there to seasoned developers.

Firstly, I noticed that there are no videos on the Algorand Python SDK on their channel. They do cover the Algorand Javascript SDKs in three separate 10-minute videos titled: 1. Deploy and Call Algorand Smart Contract, 2. Creating ASA and Asset Transfers, and 3. Creating Accounts and Payment Transactions.

I respect them and have nothing but wonderful things to say about what they've showcased on their YouTube channels; however I believe that for beginners, watching a 10-minute video with 200 pre-written lines of Javascript isn't the most effective way to learn. My videos, except for the basic setup, are over an hour long and go into each line of code in great detail. I think complex concepts need thorough explanations, not just presentations.

Take, for example, setting up a group transaction, which isn't covered in their videos. To understand this, a beginner would need to know what a list is, the importance of a GID and how to access a transaction's class attributes, and the concept of a class itself. Group transactions are just one of many topics that aren't readily available and can't be easily grasped by simply reading documentation or watching a 10 minute Javascript video, especially for newcomers.

Thank you for being the first person to provide feedback and I enjoyed speaking with you yesterday, apologies for not catching your comment here earlier!

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by atsoc1993** [comment]
Update:

The proposal is currently in review and is live via:
https://algo-learn.com/

The GitHub repository is accessible here:
https://github.com/atsoc1993/AlgoLearn

The paired YouTube tutorial series for respective chapters can be viewed at this link to YouTube playlist:
https://youtube.com/playlist?list=PLfEzhqrD5SJ05tfER-CbtSPdh2C8znO_D&si=SgYolP98tAp1Z7ap

Proposal reviewer @silentrhetoric has mentioned that at first glance there were broken links on the header/footer of the website, and some IDE components were not working across certain chapters.  

We have reiterated and believe we have fixed all instances of the above.

Another discrepancy was that the proposal states we would review ALL types of transactions, but I had no content regarding Freeze/Clawback transactions or Key Registration transactions. 

We have added chapters for these types of transactions; for Key Registration transactions we also included a guide with snippets and terminal commands needed to access relevant node information eg; selection/voting keys.

**Comment by SilentRhetoric** [comment]
Thanks for posting your update @atsoc1993.

The following issues have been identified with the AlgoLearn site:

1. The API reference link in the footer directs to a lesson page at https://algo-learn.com/python/compiling-launching-and-interacting-with-your-first-contract that does not contain an API reference. Is there an API reference to which this link should navigate? Other header and footer links appear to be correct now.
2. A previous review of the Code Editor embedded at the bottom of the lesson pages found that simple code could be run, but Algorand-related code involving the SDK would fail to run. Following your update, it now appears that the Code Editor on some lesson pages, such as https://algo-learn.com/python/getting-started-with-algorand, now prevents editing the code in the text field, and so the Editor is no longer interactive as the proposal described.
3. Running the code in the Code Editor by clicking the Show Output button, such as on https://algo-learn.com/python/getting-started-with-algorand, returns incorrect output. In one case, the code appears to make a status call to Testnet algod, and the output prints that the last round is 1234567, while Testnet is, in fact, on round 46643627+ as of this writing. It appears that the Code Editor is not running the actual code displayed on the page but rather something else.
4. Copying the code from https://algo-learn.com/python/getting-started-with-algorand to another lesson page where the Code Editor input has not been disabled and running it produces the error `Traceback (most recent call last):
  File "script.py", line 2, in <module>
    from algosdk.v2client.algod import AlgodClient
ModuleNotFoundError: No module named 'algosdk'`. From these two tests, it does not appear that the interactive IDE functionality described in the proposal is fully functional.

Some additional items are noted as part of the review:

1. The numbering of the YouTube videos does not match the structure of the chapters in the web platform, which is unintuitive. This may be a simple matter for the proposer to address to improve the integration between video and written content. 
2. A substantial amount of code content is presented throughout the chapters of the web platform, and the accuracy of this code has not been tested at this time.
3. Similarly, given that the videos at https://www.youtube.com/watch?v=z9lZ_ypTZzA&list=PLfEzhqrD5SJ05tfER-CbtSPdh2C8znO_D total over 13 hours in length, a full review of the video content has not been performed at this time.
4. Given the large amount of written and video content of a technical nature, the Foundation invites the broader community to participate in reviewing the AlgoLearn course content and sharing feedback here.
5. The review notes that the AlgoLearn course utilizes names and images of Pokemon. It is unclear to the reviewer if this is an acceptable use of what is presumably copyrighted intellectual property.

As of this comment, the review of xGov-99 is on hold with the current finding that the deliverables need improvement. In particular, the inability to run Algorand code in the platform's Code Editor is a significant deficiency in the platform's ability to enable learning and deliver the proposal as it was written. 

The Foundation can revisit this review once the four issues enumerated above have been addressed and the proposer has responded to the additional five items noted in the review.

**Comment by nonfungibleab** [comment]
Testing email reply to GitHub comment.

**Comment by atsoc1993** [comment]
> Thanks for posting your update @atsoc1993.
> 
> The following issues have been identified with the AlgoLearn site:
> 
> 1. The API reference link in the footer directs to a lesson page at https://algo-learn.com/python/compiling-launching-and-interacting-with-your-first-contract that does not contain an API reference. Is there an API reference to which this link should navigate? Other header and footer links appear to be correct now.
> 2. A previous review of the Code Editor embedded at the bottom of the lesson pages found that simple code could be run, but Algorand-related code involving the SDK would fail to run. Following your update, it now appears that the Code Editor on some lesson pages, such as https://algo-learn.com/python/getting-started-with-algorand, now prevents editing the code in the text field, and so the Editor is no longer interactive as the proposal described.
> 3. Running the code in the Code Editor by clicking the Show Output button, such as on https://algo-learn.com/python/getting-started-with-algorand, returns incorrect output. In one case, the code appears to make a status call to Testnet algod, and the output prints that the last round is 1234567, while Testnet is, in fact, on round 46643627+ as of this writing. It appears that the Code Editor is not running the actual code displayed on the page but rather something else.
> 4. Copying the code from https://algo-learn.com/python/getting-started-with-algorand to another lesson page where the Code Editor input has not been disabled and running it produces the error `Traceback (most recent call last):   File "script.py", line 2, in <module> from algosdk.v2client.algod import AlgodClient ModuleNotFoundError: No module named 'algosdk'`. From these two tests, it does not appear that the interactive IDE functionality described in the proposal is fully functional.
> 
> Some additional items are noted as part of the review:
> 
> 1. The numbering of the YouTube videos does not match the structure of the chapters in the web platform, which is unintuitive. This may be a simple matter for the proposer to address to improve the integration between video and written content.
> 2. A substantial amount of code content is presented throughout the chapters of the web platform, and the accuracy of this code has not been tested at this time.
> 3. Similarly, given that the videos at https://www.youtube.com/watch?v=z9lZ_ypTZzA&list=PLfEzhqrD5SJ05tfER-CbtSPdh2C8znO_D total over 13 hours in length, a full review of the video content has not been performed at this time.
> 4. Given the large amount of written and video content of a technical nature, the Foundation invites the broader community to participate in reviewing the AlgoLearn course content and sharing feedback here.
> 5. The review notes that the AlgoLearn course utilizes names and images of Pokemon. It is unclear to the reviewer if this is an acceptable use of what is presumably copyrighted intellectual property.
> 
> As of this comment, the review of xGov-99 is on hold with the current finding that the deliverables need improvement. In particular, the inability to run Algorand code in the platform's Code Editor is a significant deficiency in the platform's ability to enable learning and deliver the proposal as it was written.
> 
> The Foundation can revisit this review once the four issues enumerated above have been addressed and the proposer has responded to the additional five items noted in the review.

Hello Silent!

Happy to see we have access back on this thread.

The IDE's should now be fully functional for the AlgoSDK sections of "Getting started with Algorand" as well for Python, JS and GO.

We have also made some changes to the chapter layout to better fit the Youtube Playlist order.

**Comment by atsoc1993** [comment]
> Hey @atsoc1993 
> 
> The usage of the `vm2` package might be a critical problem for this to move on.
> 
> Following this: https://www.npmjs.com/package/vm2 the package is flagged as being discontinued and suffering from critical security issues!

Ahh, yes this was due to us using judge0 previously— I'll remove it from the package.json shortly but it isn't be used anywhere in the current codebase.

**Comment by atsoc1993** [comment]
> > Hey @atsoc1993
> > The usage of the `vm2` package might be a critical problem for this to move on.
> > Following this: https://www.npmjs.com/package/vm2 the package is flagged as being discontinued and suffering from critical security issues!
> 
> Ahh, yes this was due to us using judge0 previously— I'll remove it from the package.json shortly but it isn't be used anywhere in the current codebase.

Removed, I also removed a utils folder that we weren't using anymore as well.

**Comment by lazystar** [comment]
I can't quite figure out how your code editor is working (`import { executePython } from '@/utils/executePython';`). Can you shed some light on that for me?

**Comment by lazystar** [comment]
nvm, found it. so you removed the functionality entirely?

**Comment by atsoc1993** [comment]
> nvm, found it. so you removed the functionality entirely?

Yes sir! It was only being used when we had the judge0 API setup.

**Comment by atsoc1993** [comment]
Just to include notes here as well, we were told the Pokémon images must be removed— I will be blurring the image used on the website as well as its appearances in the ARC69 and ARC19 videos using the Youtube studio editor which should only take a few minutes.

**Comment by atsoc1993** [comment]
All images of Pokémon have been blurred on the YouTube content, and all images removed entirely from the AlgoLearn website. 👍

**Comment by lazystar** [comment]
Sorry to bother you, but I feel like I am looking at the wrong [repo](https://github.com/atsoc1993/AlgoLearn). I see that you are using the code editor [here](https://github.com/atsoc1993/AlgoLearn/blob/main/src/app/%5Blanguage%5D/%5BchapterTitle%5D/page.tsx#L132), calling [`runCode`](/api/code-runner), which in turn calls your own API endpoint under [`/api/code-runner`](https://github.com/atsoc1993/AlgoLearn/blob/main/src/pages/api/code-runner.ts). Following the Typescript setting [here](https://github.com/atsoc1993/AlgoLearn/blob/main/tsconfig.json#L22) (what's the motivation for this?) it should call `src/utils/execute<whatever_language>`, which was removed in [this commit](https://github.com/atsoc1993/AlgoLearn/commit/271673a77794c2fc9f227e3a1bff499eb397f4b0). Now I can't find where this is actually coming from. 🫤
Thanks for your help!

**Comment by atsoc1993** [comment]
> Sorry to bother you, but I feel like I am looking at the wrong [repo](https://github.com/atsoc1993/AlgoLearn). I see that you are using the code editor [here](https://github.com/atsoc1993/AlgoLearn/blob/main/src/app/%5Blanguage%5D/%5BchapterTitle%5D/page.tsx#L132), calling [`runCode`](/api/code-runner), which in turn calls your own API endpoint under [`/api/code-runner`](https://github.com/atsoc1993/AlgoLearn/blob/main/src/pages/api/code-runner.ts). Following the Typescript setting [here](https://github.com/atsoc1993/AlgoLearn/blob/main/tsconfig.json#L22) (what's the motivation for this?) it should call `src/utils/execute<whatever_language>`, which was removed in [this commit](https://github.com/atsoc1993/AlgoLearn/commit/271673a77794c2fc9f227e3a1bff499eb397f4b0). Now I can't find where this is actually coming from. 🫤
> 
> Thanks for your help!

(This is from Matt)

Hi @lazystar – Thanks for catching this! You’re absolutely right to question the discrepancies here. Let me try to clarify:

Fork Sync Issue:
<@357290960327016468>’s fork appears to be out of sync with the latest upstream repository. The code editor logic in this PR references deprecated files (like src/utils/execute<whatever_language>.ts), which were removed when we migrated to a Dockerized backend service in this commit.

Current Code Execution Flow:
In the main repository, the /api/code-runner endpoint now acts as a proxy to forward requests to an external backend (hosted on GCP). Here’s the current implementation:

```const BACKEND_API_URL = process.env.BACKEND_API_URL || 'http://35.226.166.220:3001/run-code';  

export default async function handler(req: NextApiRequest, res: NextApiResponse) {  
  // ... forwards code/language to the backend service  
}
```  
The old execute<whatever_language>.ts utilities are no longer part of the project.

Resolving the PR:
<@357290960327016468> and I will rebase his fork against the upstream main branch to ensure your PR reflects the latest changes. This will help us review only the new modifications introduced.

Once synced, we can focus on the specific changes to the code editor or API integration. Sorry about the confusion!"

**Comment by atsoc1993** [comment]
Good morning,

Just to clarify, the above fork rebase was done same-day @lazystar — as per email update please let me know if anything else is needed.

**Comment by lazystar** [comment]
Hey 👋
Code makes more sense now!
Last problem: the code editor doesn't seem to work atm. 😕

**Comment by atsoc1993** [comment]
Hello! As per email this was just a VPS autopay issue (which sadly resulted in the instance being terminated), — we'll be uploading the backend onto a new VPS and should be online ASAP! Hoping to have this done by end-of-day.

**Comment by atsoc1993** [comment]
@lazystar IDE's are back online!

**Pull request merged**
