### PR TITLE
xGov-75 Social Impact Staking for Algo governance

### PR DESCRIPTION
**Pull request by CashdilloXGov**
Innovative mechanism for generating Impact grants out of ALGO governance cycles

### CODE REVIEW

**Comment by makman88** [comment]
Bravo! Love this proposal. Happy to see a mechanism where our donation can be routed to the DAO without the need to take initial possession of funds, for obvious taxation reasons.

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Comment by CashdilloXGov** [comment]
Hi,
Where is the link to post it to the Forum?
Thanks,
Alex


________________________________

**Comment by CashdilloXGov** [comment]
> Proposer, please post your algorand forum discussion thread link here. Thank you.

Here it is: https://forum.algorand.org/t/social-impact-staking-proposal-for-next-governance-round/11331?u=cashdillo

**Comment by CashdilloXGov** [comment]
Our proposal and advocacy piece for Social Impact Staking can be seen on the Algorand Forum in this thread. Please do share and support if you are a believer. https://forum.algorand.org/t/social-impact-staking-proposal-for-next-governance-round/11331

**Comment by CashdilloXGov** [comment]
Thanks, here is our thread in the forum: https://forum.algorand.org/t/social-impact-staking-proposal-for-next-governance-round/11331
[https://global.discourse-cdn.com/business6/uploads/algorand/original/1X/3c9bc109197c3de404a51dd7077567d5e7bf2316.png]<https://forum.algorand.org/t/social-impact-staking-proposal-for-next-governance-round/11331>
Social Impact Staking_proposal for next governance round<https://forum.algorand.org/t/social-impact-staking-proposal-for-next-governance-round/11331>
A proposal to implement impact staking options for governors: xGov-75 Social Impact Staking for Algo governance by CashdilloXGov · Pull Request #75 · algorandfoundation/xGov · GitHub More on the why here in this Medium article. Why Social Impact Staking (SIS) for Algorand governors? Because it’s in the spirit of Silvio Micali and Algorand. | by Cashdillo | Medium Please support the proposal! We can all give something back through Social Impact Staking. We can make giving automatically part of...
forum.algorand.org



________________________________

**Comment by SudoWeezy** [comment]
Proposal have been removed, you can see the reason there https://github.com/algorandfoundation/xGov/pull/174

**Pull request merged**
