### PR TITLE
xGov-144: Cosmic Champs x AlgoLeagues - Cross-community 3D NFT Collab

### PR DESCRIPTION
**Pull request by madshapes-dev**
Sample of our past collab NFT's.

image

### CODE REVIEW

**Review by madshapes-dev — COMMENTED** [review]
//

**Review by madshapes-dev — COMMENTED** [review]
update discussions link

**Review by madshapes-dev — COMMENTED** [review]
adding timeline + funding schedule

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Pull request merged**
