### PR TITLE
xGov-41: minthol, the next-gen loyalty program platform

### PR DESCRIPTION
**Pull request by solkimicreb**
A draft proposal. I had some problems with the validator and external links, please see [this issue](https://github.com/algorandfoundation/xGov/issues/40) for discussion.

Edit: my issues are cleared up, thanks! I am fixing them.

Thanks!

### CODE REVIEW

**Comment by nonfungibleab** [comment]
Hi, please also engage with the community about your project at the Algorand Forum 
https://forum.algorand.org/t/xgov-41-minthol-art-the-next-generation-loyalty-program-and-coupon-platform/9942

**Comment by solkimicreb** [comment]
Hi! I will fix and finalize things today. I am also checking the forum in a sec, thanks for the heads up!

**Comment by solkimicreb** [comment]
Hi @nonfungibleab ! I fixed the name and external links and set the proposal status to final. I hope everything else is okay. I will also keep an eye on the algo forums.

Thanks!

**Comment by ShaperOfEntropy** [comment]
I really like the idea since it is a straightforward, real-life application of blockchain and a great use of NFTs.
The project seems well-thought-out: it has an interesting business model, multiple sources of revenue to become sustainable, and envisions team enlargement to deliver on the ambitious goals. I especially like the vision of using the blockchain in the background and not bothering the users with it unless they want to.

Some comments on how the proposal itself could be further improved:
1) Include links to your experiences (e.g. LinkedIn or projects) for convenience for xGovs to easily verify your claims.
2) Under point # 3, there is no video link.
3) The structure is rather difficult to follow, especially to see what you are even asking the xGovs to fund. If I understand correctly, you intend to develop a (mobile?) app for scanning of QR codes and reading of NFC tags that represent physical coupons? Also for the perk discovery and registration system, could you describe in more detail how that will look like - so that xGovs will be able to verify that you delivered on the promise.
4) Include your competition analysis - both in physical and blockchain space; to address why is your product better and what's the market size? Similar as you addressed it on [the Forum](https://forum.algorand.org/t/xgov-41-minthol-art-the-next-generation-loyalty-program-and-coupon-platform/9942/3).
5) How will the grant be spent? Will ALGO be sold on the market? If yes, using DEXs or CEXs? Or will a loan be taken against it in DeFi/CeFi? Would you perhaps be willing to vest the awarded funds?

**Comment by solkimicreb** [comment]
@ShaperOfEntropy Thanks! I don't think I can modify my xgov entry anymore, which is fine. It is how it should work. I will modify and expand my "whitepaper" though.

Quick answers here in the meantime:

1. I am not a big fan of LinkedIn but I can add links to my OSS projects, talks, and articles.

2. Thanks, will fix it. That part is going to be added to the platform in a few weeks max too.

3. Yeah, I get this feedback often. I will try to clarify things. I won't work on a traditional app for now and stick with a (progressive) web app (web page). App stores are picky and it's difficult for crypto projects to qualify, especially if they include payments in crypto. App stores are also picky when it comes to porn and adult content and I don't intend to censor my platform, rather let the community do the work via subdomain filtered sites. These subdomains will also serve as kind of whitelabel solutions for loyalty programs of big brands which do not wish to display the minthol brand. Whitelabel is also something that does not pair well with apps. You can't really upload 100s of versions of the "same" app with different skin to the store. 

I am working to provide an experience as close as possible to traditional apps though. The recent web API developments make this possible imo.

4. Yeah, I plan to work on this. It will take some time though. I want to triple-check numbers about competitors before I publish anything.

5. Spending the grant largely depends on my next few months. I am actively trying to raise funds and as it is going badly, I am also working on monetizing the product ASAP. If none of these work out I will probably sell the funds in multiple steps but in a relatively short timeframe to fund myself. Otherwise, I will keep it as capital for future expansion when favorable market arrives. I am not planning to take a loan against it either way.

**Pull request merged**
