### PR TITLE
xgov-195-arcpay.md

### PR DESCRIPTION
**Pull request by Wild-er**
First draft of Arcpay xGov proposal.

### CODE REVIEW

**Comment by gabrielkuettel** [comment]
Hi @Wild-er - I'm with the DevReal team at Foundation reviewing the technical deliverables of your proposal. Before proceeding, I have some feedback and questions:

**Documentation**:

The documentation is well organized and written clearly, but some areas could use expansion:

1. Please add an explanation of the "status" field (Active, Pending, Canceled, Closed) and how to manage listing states.
2. In the [SDK initialization examples](https://docs.arcpay.dev/introduction/sdk-integration.html#usage), please demonstrate initialization on both Algorand and Voi networks.
4. Please document frequently mentioned interfaces, like the [Listing](https://docs.arcpay.dev/introduction/sdk-integration.html#usage) interface. 

**Dashboard/UI**:

I successfully tested several features, including authentication, creating organizations, managing members via invitations, generating API keys, and generating listings. However, ran into issues with the following:

1. When testing the Buy flow, the "Buy" button is missing from the modal. Maybe because my listings were in a `pending` state? Would be helpful to document what this means and how to promote a listing from `pending` to `active` (as mentioned above).
2. Images for NFTs (in my case arc3) did not load in the listing creation or buy modal. 
3. Because I was unable to complete the buy flow, I could not evaluate the dashboard's transaction and metrics display features.

**Security**

When initializing the SDK in a browser environment, any API keys included in the client-side code are exposed to users. While you're restricting requests by domain, keep in mind that if you're checking the `origin` header of the request, this can be spoofed using a reverse proxy or other tools.

Potential Solutions:

1. Treat the client-side key as a "publishable" key (similar to Stripe's public API keys) with limited permissions
2. Add documentation explaining that anyone can create external listings for your organization using these public keys
3. Move SDK initialization to the server side where sensitive credentials can be kept private

Let me know if I'm misunderstanding your security posture here. The main consideration is whether you want these operations to be publicly accessible. If not, the authentication should be handled server-side where keys can remain private.

**SDK**: 

During SDK testing, I successfully tested several core features, including initializing the client, retrieving listings, and creating listings. However, I encountered an issue when trying to buy listings, as the modal failed to load properly. I tested the integration using a vanilla React/TypeScript project bootstrapped with Vite. 

I'd appreciate your feedback on these findings and would be happy to discuss potential solutions. Please let me know if you'd like clarification on any specific points, you see a different approach to these issues, or if I've misunderstood any aspects of your current implementation. 

Thank you!

**Comment by Wild-er** [comment]
We have implemented updates that should address all issues raised.

Looking forward to the next review!

**Comment by Wild-er** [comment]
Updates: 
- Improved documentation around IPFS Gateway's for SDK users who hit limits
- ARC3, ARC19, ARC69 image loading stability with lazy loading
- Token images now appear, sourced from https://asa-list.tinyman.org/ 
- Asset amounts now appear in the selection tool
- Fixed bug with asset selection

**Comment by gabrielkuettel** [comment]
Thanks for addressing the feedback! Nicely done, I'll be moving this forward in the process. Thank you.

**Pull request merged**
