### PR TITLE
xGov-105 Cheaper USDC Onramp/Offramp for US Algorand Users -> To withdraw

### PR DESCRIPTION
**Pull request by pescennius**
Cheaper USDC Onramp/Offramp for US Algorand Users

### CODE REVIEW

**Review by pescennius — COMMENTED** [review]
done

**Review by pescennius — COMMENTED** [review]
done

**Comment by SudoWeezy** [comment]
Be sure to change the status to Final if you want to be part of the next session 
`status: Draft` -> `status: Final`

**Comment by nonfungibleab** [comment]
Proposer, please post your algorand forum discussion thread link here. Thank you.

**Pull request closed without merging**
