### PR TITLE
xGov-101 - Visual Studio Code Extension for TEAL

### PR DESCRIPTION
**Pull request by dragmz**
Please feel welcome to discuss my proposal here.

### CODE REVIEW

**Comment by Vidhyanandcs** [comment]
1) With algokit 2.0 do you still see a need for such a tool? if yes, why?
2) What is the amount requested as funding for completion of the project?

**Comment by dragmz** [comment]
> 1. With algokit 2.0 do you still see a need for such a tool? if yes, why?

Yes, I do. TEAL isn't going anywhere with AlgoKit 2.0 as far as I'm aware. It's the extra Python -> TEAL compiler being added and not the AVM moving away from TEAL.

> 2. What is the amount requested as funding for completion of the project?

I'll get this estimtaed some time closer to the submission deadline.

**Comment by Vidhyanandcs** [comment]
> > 1. With algokit 2.0 do you still see a need for such a tool? if yes, why?
> 
> Yes, I do. TEAL isn't going anywhere with AlgoKit 2.0 as far as I'm aware. It's the extra Python -> TEAL compiler being added and not the AVM moving away from TEAL.
> 
> > 2. What is the amount requested as funding for completion of the project?
> 
> I'll get this estimtaed some time closer to the submission deadline.

All the very best.

**Comment by SilentRhetoric** [comment]
With the recent release of the AlgoKit AVM Debugger VSCode extension by the Algorand Foundation, could you help us understand how the extension being proposed here would be better or different than the official AlgoKit version?

[https://marketplace.visualstudio.com/items?itemName=AlgorandFoundation.algokit-avm-vscode-debugger](https://marketplace.visualstudio.com/items?itemName=AlgorandFoundation.algokit-avm-vscode-debugger)

**Comment by dragmz** [comment]
> With the recent release of the AlgoKit AVM Debugger VSCode extension by the Algorand Foundation, could you help us understand how the extension being proposed here would be better or different than the official AlgoKit version?
> 
> https://marketplace.visualstudio.com/items?itemName=AlgorandFoundation.algokit-avm-vscode-debugger

The tool mentioned is a debugger and does not provide the LSP features I'm proposing here.

**Pull request closed without merging**
